### PR TITLE
Fix process_frame to make the last clip satisfy the min_scene_len

### PR DESCRIPTION
**Pull request by Tsunehiko**
## Problem
When splitting a video, even though the `min_scene_len` was set, a video with a shorter length than that was generated.
This problem is related to #150. (I believe that this is a problem that could not be solved with #105.)

## Cause
This is because the length of the last clip is not compared to `min_scene_len`.

## Solution
Fixed to pass the length of the entire video (`total_frames`) to `process_frame()` and compare the length of the last clip to `min_scene_len`.

### CODE REVIEW

**Comment by Tsunehiko** [comment]
Added some changes for splitting the video starting in the middle.

**Comment by Breakthrough** [comment]
Thanks for the PR.  Unfortunately this is a breaking API change, so it cannot be merged as-is (v0.5.x is closed for breaking changes now).  Coincidentally I just addressed this case in the v1.0 refactor, so this is already in place for that (short scenes will be merged with their predecessors or successors):
https://github.com/Breakthrough/PySceneDetect/blob/d654c831f7bbb1f0f03b04e27f7f67e479fd84b7/scenedetect/scene_manager.py#L559

However, I think we could achieve the same thing in v0.5 but as a post-processing stage, since the actual # of frames processed may exceed the reported video length.  This could probably be done pretty quickly here:
https://github.com/Breakthrough/PySceneDetect/blob/master/scenedetect/cli/context.py#L326

Then this logic could also be done purely within the command-line and not break the API.  I will mark this as a known issue on the v0.5 API as well.

If you wish to refactor it accordingly let me know, otherwise I can submit a patch to fix it.  Thanks for the PR.

**Comment by Tsunehiko** [comment]
Thank you for your kind reply. I encountered this bug while using the Python API (not using the command line).
I used `ContentDetector` with threshold set to 7 and min_scene_len set to 180, but a 0.02sec clip was generated for a 50fps video. This bug occurred in several videos, and the common feature was that only the length of the last clip was shorter than min_scene_len. As you wrote, I think it is safer to deal with it in the post-process stage. v1.0 will solve this problem, and I think the Python API support is less important and only the command line should be dealt with in the way you suggested. I'd like to get involved, as it's a rare opportunity, but I can't make time next week, so it'll be in about 10 days, if that's okay with you? If there is no problem, I will create the issue. Finally, I'm very excited about the next v1.0.

**Comment by Breakthrough** [comment]
Not a problem at all, we're glad to have people like you that are willing to get involved and help out!  I know how difficult it can be to find time to work on open source projects, so no rush.  We really appreciate your help!

One other option that came to mind was, we could add a new argument to `get_scene_list()` in `SceneManager` to also set the minimum scene length, and perform this processing stage there (along with `drop_short_scenes`).  So long as there are default values provided for both of those arguments, then that will not be a breaking change.  The benefit there is that would also fix the Python API while still maintaining backwards compatibility.

I am ok with either approach, and more than willing to consider any other alternatives you might think of or want to explore.  Many thanks for your interest and help with the project!

**Comment by Breakthrough** [comment]
Closing as a fix for #266 is now in the v0.6 branch which has a new `--merge-last-scene` option to enable this behaviour.

**Pull request closed without merging**
