### PR TITLE
Correct RFC number

### PR DESCRIPTION
**Pull request by leingang**
RFC 4180 is the one that describes CSV files.

### CODE REVIEW

**Review by Breakthrough — CHANGES_REQUESTED** [review]
Could you also update the text in the command-line itself:
https://github.com/Breakthrough/PySceneDetect/blob/master/scenedetect/cli/__init__.py#L711=

Thank you for noticing this and for the PR.

**Comment by leingang** [comment]
Done! Sorry I didn't think to find and fix them all in one commit.

**Comment by leingang** [comment]
I think that's all of them now!

**Comment by Breakthrough** [comment]
Thank you for the PR!

**Pull request merged**
