### PR TITLE
Modify `--min-duration` arguments to accept a timecode instead of frame numbers

### PR DESCRIPTION
**Pull request by tonycpsu**
* Add new `-m`/`--min-duration` option for specifying a minimum number
  of seconds for each scene.
* Scenes shorter than this value will be merged with subsequent
  scenes, or if `-M`/`--min-duration-action` is set to `drop`, dropped
  from the scene list entirely.

### CODE REVIEW

**Comment by Breakthrough** [comment]
I like where this PR is going in terms of maintainability, but this essentially depreciates the `--min-scene-len` option for both `detect-content` and `detect-threshold`.  I'm open to that for sure to make adding detectors easier in the future, but would like to make sure the existing detectors are modified accordingly to remove the redundant option.

(Or was there a reason you kept `-m` for the detectors as well that I might be missing?  Just want to discuss this briefly before making any decisions, thanks for the PR!)

**Comment by tonycpsu** [comment]
Er, I wish I had a better answer than "I completely forgot about `--min-scene-len`, but I don't... 🙈

I do think there's merit in using seconds rather than frames, as FPS varies, and I kind of feel like most people would want to specify a number of seconds.  But that would break backwards compatibility for not much gain...

I also think the option to have short scenes prepended/appended to neighbors might be valuable to some, but it wasn't really my primary motivation for this, so maybe this was just a poorly-conceived idea.

Will check out if `--min-scene-len` works for my purposes.

**Comment by Breakthrough** [comment]
One other option which might work is modifying `--min-scene-len` to accept [a timecode](https://pyscenedetect-manual.readthedocs.io/en/latest/cli/commands.html#timecode-formats) instead of number of frames.  I completely agree that there is merit in using a unit other than frames for that purpose; for transparency, the `--min-scene-len` option was added before PySceneDetect actually supported timecodes.

Now that the parsing is done for them though, modifying `--min-scene-len` to accept any of the timecode formats would be trivial (all the parsing work is done if you look at the `time` command).

Thoughts?

**Comment by tonycpsu** [comment]
For now, I've just reverted my implementation and added timecode parsing for the existing option as you suggested.

I do think there's merit to allowing users to drop short scenes (it appears the current implementation just prepends them to the next scene?), and maybe some simplicity to doing it after the scene list is generated instead of in the detection code, but this'll do for now.

**Comment by Breakthrough** [comment]
Thanks so much for this, @tonycpsu!  Sorry I don't have a Travis.CI setup for the project yet, so still need to run all the unit tests on this before merging, but I don't expect any issues (again thank you for submitting very small/targeted code changes, it really helps!)

**Comment by Breakthrough** [comment]
Tested manually for now; still requires documentation update.  Will try to get that pushed to this PR so it can go in for this weekend.

Sorry for the delay, and thanks again for your submission!

**Comment by Breakthrough** [comment]
Documentation updated in latest ( https://pyscenedetect-manual.readthedocs.io/en/latest/cli/detectors.html ).  Default value for both -m options changed from 15 frames to 0.6 seconds.  Feel free to provide any comments if you feel this new default isn't a good choice, or if you notice anything in the new documentation.

Thanks again for the pull request!

**Pull request merged**
